# Error Handling
Probably in A1 you have seen your node.js server crashes because of an error. And Hopefully, you have tried to handle these errors. In this tutorial, I will show you the basics of error handling. 

It is not just the user experience that dictates why we should care for error handling. Node.js error handling is a must if we want our program to be secure, resilient, high-performing and bug-free, 

---
# Errors

<blockquote>
Applications running in Node.js will generally experience four categories of errors:

- Standard JavaScript errors such as <EvalError>, <SyntaxError>, <RangeError>, <ReferenceError>, <TypeError>, and <URIError>.
- System errors triggered by underlying operating system constraints such as attempting to open a file that does not exist or attempting to send data over a closed socket.
- AssertionErrors are a special class of error that can be triggered when Node.js detects an exceptional logic violation that should never occur. These are raised typically by the node:assert module.
All JavaScript and system errors raised by Node.js inherit from, or are instances of, the standard JavaScript <Error> class and are guaranteed to provide at least the properties available on that class.
- User-specified errors triggered by application code.
</blockquote>

In your case, I think you should be mostly interested in `User-specified errors`. We want to 
- define our own error so the non-technical user don't see a big msg from the server but instead sees a friendly error msg that is human-centric and well-documented in the API doc.

<img src="https://cdn.discordapp.com/attachments/1017862173881544775/1027444384452591636/unknown.png"  width="300" >

vs.

<img src="https://cdn.discordapp.com/attachments/1017862173881544775/1027444694592016404/unknown.png"  width="300" >

- trigger them, using the `throw` keyword
- and handle them so the node.js process don't crash 

---

# Error propagation and interception 
## Synchronous Code  
###  Standard JavaScript errors
- These are handled using the try…catch construct provided by the JavaScript language.

```js
// Throws with a ReferenceError because z is not defined.
try {
  const m = 1;
  const n = m + z;
} catch (err) {
  // Handle the error here.
}
```
if the error is not handled, the node.js process will exit immediately. 

## ASynchronous Code  
### A callback function
A callback function will accept an Error object passed as the first argument to that function. If that first argument is not null and is an instance of Error, then an error occurred that should be handled.
```js
const fs = require('node:fs');
fs.readFile('a file that does not exist', (err, data) => {
  if (err) {
    console.error('There was an error reading the file!', err);
    return;
  }
  // Otherwise handle the data
});
```

Errors generated in this code cannot be intercepted using try…catch as they are thrown after the calling code has already exited.

### Promises can use the `catch` method to catch an thrown error. 
### Async/Await should use `try..catch` block to catcn a thrown error.

---
# Class: Error
All errors generated by Node.js, including all system and JavaScript errors, will either be instances of, or inherit from, the Error class.

# Error Object
The first thing to know about Node.js error handling is the error object. Each object has a type and a string message

Here is how we set a message for an object of type Error:

```js
throw new Error('Poke Error, please check your ...');
```

And here is how we set a message for an object of our own type:

```js
class PokemonAPIError extends Error {
    constructor(args){
        super(args);
        this.name = "PokemonAPIError"
    }
}

console.log(new Error('A standard error'))
// { [Error: A standard error] }

console.log(new PokemonAPIError('Poke Error, please check your ...'))
// { [Your fancy error: An augmented error] name: 'FancyError' }
```

output
```
PS C:\COMP 4537\comp4537repo\Labs\Lab 5 - Error Handling>nodemon .\test.js
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node .\test.js`
Error: A standard error
    at Object.<anonymous> (C:\COMP 4537\comp4537repo\Labs\Lab 5 - Error Handling\test.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

PokemonAPIError: Poke Error, please check your ...
    at Object.<anonymous> (C:\COMP 4537\comp4537repo\Labs\Lab 5 - Error Handling\test.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
[nodemon] clean exit - waiting for changes before restart

```

## Throw?
Throw really does two things: it stops the program, and it finds a 
<blockquote>
When JavaScript finds a throw keyword, the first thing it does is stop dead in its tracks. This event prevents any more functions from running. By stopping like this, it mitigates the risk of any further errors occurring and helps debug programs easily.
With the program halted, JavaScript will begin to trace the daisy chain of functions that were called in order to reach a catch statement. This chain is called the call stack (don’t worry – we’ll get to the call stack soon). The nearest catch that JavaScript finds is where the thrown exception emerges. If no try/catch is found, the exception throws, and the Node.js process exits, causing the server to restart.
</blockquote>


<!-- # Exceptions vs. errors
> A JavaScript exception is a value that is thrown as a result of an invalid operation or as the target of a throw statement. While it is not required that these values are instances of Error or classes which inherit from Error, all exceptions thrown by Node.js or the JavaScript runtime will be instances of Error. -->



